import Crush.Metatheory.Datatype.Core

/-!
# Canonical semantics of intrinsic datatype blocks

`Val` is the free, finite algebra generated by a datatype block. External fields
carry values supplied by the surrounding model; recursive fields carry another
finite value from the same mutual block. Thus no-confusion and well-foundedness
are consequences of the representation, not additional axioms.
-/

namespace Crush.Metatheory.Datatype

universe u v

mutual
  /-- Finite values freely generated by a mutual datatype block. -/
  inductive Val {arity : Nat} (block : Block arity)
      (Base : BaseSort → Type u) : DataRef block → Type u where
    | ctor {data : DataRef block} {ctor : CtorDecl arity} :
        CtorRef block data ctor → Args block Base ctor.fields →
        Val block Base data

  /-- Heterogeneous constructor arguments in declaration order. -/
  inductive Args {arity : Nat} (block : Block arity)
      (Base : BaseSort → Type u) : List (FieldDecl arity) → Type u where
    | nil : Args block Base []
    | base {name : String} {sort : BaseSort} {rest : List (FieldDecl arity)} :
        Base sort → Args block Base rest →
        Args block Base ({ name := name, sort := .base sort } :: rest)
    | data {name : String} {data : DataRef block}
        {rest : List (FieldDecl arity)} :
        Val block Base data → Args block Base rest →
        Args block Base ({ name := name, sort := .data data } :: rest)
end

namespace FieldDecl

/-- Semantic carrier of one constructor field. -/
def Denote {arity : Nat} (block : Block arity) (Base : BaseSort → Type u)
    (field : FieldDecl arity) : Type u :=
  match field.sort with
  | .base sort => Base sort
  | .data data => Val block Base data

end FieldDecl

mutual
  /-- Map all external field payloads while preserving constructor structure. -/
  def Val.map {arity : Nat} {block : Block arity}
      {Source : BaseSort → Type u} {Target : BaseSort → Type v}
      (mapBase : ∀ sort, Source sort → Target sort) :
      {data : DataRef block} → Val block Source data → Val block Target data
    | _, .ctor ctor args => .ctor ctor (args.map mapBase)

  /-- Pointwise external-payload map for constructor arguments. -/
  def Args.map {arity : Nat} {block : Block arity}
      {Source : BaseSort → Type u} {Target : BaseSort → Type v}
      (mapBase : ∀ sort, Source sort → Target sort) :
      {fields : List (FieldDecl arity)} →
        Args block Source fields → Args block Target fields
    | _, .nil => .nil
    | _, .base value rest => .base (mapBase _ value) (rest.map mapBase)
    | _, .data value rest => .data (value.map mapBase) (rest.map mapBase)
end

mutual
  /-- Height of a finite canonical datatype value. -/
  def Val.height {arity : Nat} {block : Block arity}
      {Base : BaseSort → Type u} :
      {data : DataRef block} → Val block Base data → Nat
    | _, .ctor _ args => args.height + 1

  /-- Maximum height of the recursive values in a constructor telescope. -/
  def Args.height {arity : Nat} {block : Block arity}
      {Base : BaseSort → Type u} :
      {fields : List (FieldDecl arity)} → Args block Base fields → Nat
    | _, .nil => 0
    | _, .base _ rest => rest.height
    | _, .data value rest => max value.height rest.height
end

/-- Read one typed field from a matching constructor argument telescope. -/
def Args.get {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} :
    {fields : List (FieldDecl arity)} → Args block Base fields →
    {field : FieldDecl arity} → Ref fields field → field.Denote block Base
  | _, .base value _, _, .here => value
  | _, .base _ rest, _, .there ref => rest.get ref
  | _, .data value _, _, .here => value
  | _, .data _ rest, _, .there ref => rest.get ref

/-- Every recursive field is no taller than its complete constructor
telescope. -/
def FieldDecl.HeightLe {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} (field : FieldDecl arity)
    (value : field.Denote block Base) (bound : Nat) : Prop :=
  match field with
  | ⟨_, .base _⟩ => True
  | ⟨_, .data _⟩ => value.height ≤ bound

theorem FieldDecl.HeightLe.mono {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {field : FieldDecl arity}
    {value : field.Denote block Base} {left right : Nat}
    (holds : field.HeightLe value left) (le : left ≤ right) :
    field.HeightLe value right := by
  cases field with
  | mk name sort =>
      cases sort with
      | base => trivial
      | data => exact Nat.le_trans holds le

theorem Args.get_height_le {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {fields : List (FieldDecl arity)}
    (args : Args block Base fields) {field : FieldDecl arity}
    (ref : Ref fields field) :
    field.HeightLe (args.get ref) args.height := by
  induction ref with
  | here =>
      cases args with
      | base value rest => trivial
      | data value rest => exact Nat.le_max_left _ _
  | there ref ih =>
      cases args with
      | base value rest => exact ih rest
      | data value rest =>
          exact FieldDecl.HeightLe.mono (ih rest) (Nat.le_max_right _ _)

/-- Every recursive constructor field has strictly smaller height than the
value containing it. -/
theorem Args.get_height_lt_ctor {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {fields : List (FieldDecl arity)}
    (args : Args block Base fields) {name : String}
    {child : DataRef block}
    (fieldRef : Ref fields { name := name, sort := FieldSort.data child })
    {data : DataRef block} {ctor : CtorDecl arity}
    (ctorRef : CtorRef block data ctor)
    (fields_eq : ctor.fields = fields) :
    (args.get fieldRef).height <
      (Val.ctor ctorRef (fields_eq ▸ args)).height := by
  subst fields
  exact Nat.lt_succ_of_le (args.get_height_le fieldRef)

/-- The constructor represented by `ctor` built from `args`. -/
abbrev mk {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {ctor : CtorDecl arity} (ref : CtorRef block data ctor)
    (args : Args block Base ctor.fields) : Val block Base data :=
  .ctor ref args

/-- Constructor application is injective in its argument telescope. -/
theorem ctor_inj {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {ctor : CtorDecl arity} (ref : CtorRef block data ctor)
    {left right : Args block Base ctor.fields}
    (equal : mk ref left = mk ref right) : left = right := by
  grind

/-- Distinct constructor positions build distinct datatype values. -/
theorem ctor_ne {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {leftCtor rightCtor : CtorDecl arity}
    (leftRef : CtorRef block data leftCtor)
    (rightRef : CtorRef block data rightCtor)
    (different : Ref.index leftRef ≠ Ref.index rightRef)
    (left : Args block Base leftCtor.fields)
    (right : Args block Base rightCtor.fields) :
    mk leftRef left ≠ mk rightRef right := by
  grind

/-- Every canonical value was built by one constructor in its declaration. -/
theorem ctor_cases {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    (value : Val block Base data) :
    ∃ ctor, ∃ ref : CtorRef block data ctor,
      ∃ args : Args block Base ctor.fields, value = mk ref args := by
  cases value with
  | ctor ref args => exact ⟨_, ref, args, rfl⟩

/-- A value has the constructor at the selected declaration position. -/
def IsCtor {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {ctor : CtorDecl arity} (ref : CtorRef block data ctor)
    (value : Val block Base data) : Prop :=
  ∃ args : Args block Base ctor.fields, mk ref args = value

/-- A constructor tester accepts the matching constructor. -/
@[simp] theorem test_ctor {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {ctor : CtorDecl arity} (ref : CtorRef block data ctor)
    (args : Args block Base ctor.fields) :
    IsCtor ref (mk ref args) :=
  ⟨args, rfl⟩

/-- A constructor tester rejects a distinct constructor position. -/
theorem test_ne {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {leftCtor rightCtor : CtorDecl arity}
    (leftRef : CtorRef block data leftCtor)
    (rightRef : CtorRef block data rightCtor)
    (different : Ref.index leftRef ≠ Ref.index rightRef)
    (args : Args block Base rightCtor.fields) :
    ¬IsCtor leftRef (mk rightRef args) := by
  rintro ⟨left, equal⟩
  exact ctor_ne leftRef rightRef different left args equal

/-- Total selector semantics. SMT leaves a selector unconstrained on values of
another constructor, represented here by the explicit `fallback`. -/
noncomputable def sel {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {ctor : CtorDecl arity} (ctorRef : CtorRef block data ctor)
    {field : FieldDecl arity} (fieldRef : FieldRef ctor field)
    (fallback : field.Denote block Base) (value : Val block Base data) :
    field.Denote block Base := by
  classical
  exact if h : IsCtor ctorRef value then
      (Classical.choose h).get fieldRef
    else
      fallback

/-- A selector recovers its field on the matching constructor. -/
@[simp] theorem sel_ctor {arity : Nat} {block : Block arity}
    {Base : BaseSort → Type u} {data : DataRef block}
    {ctor : CtorDecl arity} (ctorRef : CtorRef block data ctor)
    {field : FieldDecl arity} (fieldRef : FieldRef ctor field)
    (fallback : field.Denote block Base) (args : Args block Base ctor.fields) :
    sel ctorRef fieldRef fallback (mk ctorRef args) = args.get fieldRef := by
  rw [sel, dif_pos (test_ctor ctorRef args)]
  have chosen := Classical.choose_spec (test_ctor ctorRef args)
  have equal : Classical.choose (test_ctor ctorRef args) = args :=
    ctor_inj ctorRef chosen
  exact congrArg (fun fields => fields.get fieldRef) equal

/-- Try to build one constructor telescope using candidate values for recursive
fields. External fields use unit because productivity depends only on recursive
shape. -/
def Args.seed? {arity : Nat} {block : Block arity}
    (next : ∀ data : DataRef block, Option (Val block (fun _ => Unit) data)) :
    (fields : List (FieldDecl arity)) →
      Option (Args block (fun _ => Unit) fields)
  | [] => some .nil
  | { name, sort := .base sort } :: rest => do
      let tail ← Args.seed? next rest
      pure (.base () tail)
  | { name, sort := FieldSort.data child } :: rest => do
      let value ← next child
      let tail ← Args.seed? next rest
      pure (.data value tail)

/-- Find the first constructor whose recursive fields have candidate values. -/
def firstSeed? {arity : Nat} {block : Block arity}
    (next : ∀ data : DataRef block, Option (Val block (fun _ => Unit) data))
    {data : DataRef block} :
    (ctors : List (CtorDecl arity)) →
    ({ctor : CtorDecl arity} → Ref ctors ctor → CtorRef block data ctor) →
      Option (Val block (fun _ => Unit) data)
  | [], _ => none
  | ctor :: rest, lift =>
      match Args.seed? next ctor.fields with
      | some args => some (mk (lift .here) args)
      | none => firstSeed? next rest (fun ref => lift (.there ref))

/-- Search for a finite value of one datatype. Fuel bounds the height of the
constructor tree, while constructor and field traversal are structurally total. -/
def seed? {arity : Nat} (block : Block arity) :
    Nat → (data : DataRef block) → Option (Val block (fun _ => Unit) data)
  | 0, _ => none
  | fuel + 1, data =>
      firstSeed? (fun child => seed? block fuel child) data.decl.ctors
        (fun ref => ref)

/-- A block is productive when every datatype has at least one finite
constructor tree. Taking unit payloads makes this independent of external field
carriers. -/
def Productive {arity : Nat} (block : Block arity) : Prop :=
  ∀ data : DataRef block, Nonempty (Val block (fun _ => Unit) data)

namespace Block

/-- Executable productivity check. A productive block of `arity` sorts has a
shortest constructor tree of height at most `arity` for every sort. -/
def productive {arity : Nat} (block : Block arity) : Bool :=
  (List.ofFn fun data : Fin arity => data).all fun data =>
    (seed? block arity data).isSome

/-- The executable check returns an explicit finite value for every sort. -/
theorem productive_sound {arity : Nat} (block : Block arity)
    (checked : block.productive = true) : Productive block := by
  intro data
  have present : data ∈ List.ofFn (fun data : Fin arity => data) := by simp
  have found : (seed? block arity data).isSome = true := by
    simpa [productive] using List.all_eq_true.mp checked data present
  cases equal : seed? block arity data with
  | none => simp [equal] at found
  | some value => exact ⟨value⟩

end Block

/-- Productivity plus nonempty external carriers makes every datatype carrier
nonempty. -/
theorem val_nonempty {arity : Nat} {block : Block arity}
    (productive : Productive block)
    {Base : BaseSort → Type u}
    (baseNonempty : ∀ sort, Nonempty (Base sort))
    (data : DataRef block) : Nonempty (Val block Base data) := by
  let seed := Classical.choice (productive data)
  exact ⟨seed.map fun sort _ => Classical.choice (baseNonempty sort)⟩

/-- Productivity implies that every datatype declaration has a constructor. -/
theorem ctors_nonempty {arity : Nat} {block : Block arity}
    (productive : Productive block) (data : DataRef block) :
    data.decl.ctors ≠ [] := by
  intro empty
  let ⟨value⟩ := productive data
  cases value with
  | ctor ref args =>
      change Ref data.decl.ctors _ at ref
      rw [empty] at ref
      cases ref

end Crush.Metatheory.Datatype
