import Crush.Translation.Attr
import Crush.Translation.Theories
import Crush.Translation.Translate
import Crush.SMT.Quote
open Lean Meta

/-!
# Default head-indexed SMT lowerings

Encodings in this module use the same public `@[crush_lower target]` API available to
downstream users. They are kept out of the structural translator so support for library
constants can grow without extending its central pattern match.

Each lowering is exact for Lean's semantics and declines applications it cannot identify
soundly. In particular, overloaded operations check their type and canonical typeclass
instance; an explicitly supplied custom instance remains uninterpreted.
-/

namespace Crush.DefaultLowerings

open Crush SMT

/-! ## Proof-carrying logical primitive hooks -/

/-- Boolean negation restricted certified registry. Its executable
handler is generated by `CertifiedPrimitiveMapping.handler`; the semantic proof
and the two explicit external interpretation assumptions live in
`Metatheory.BuiltinHooks.notCertificate`. -/
@[crush_certified_lower Not]
def certifiedNot : CertifiedPrimitiveMapping :=
  .ofCertificate ``Not "not" 0 ⟨Metatheory.BuiltinHooks.notCertificate⟩

/-! ## Decisions and dependent decision procedures

`Decidable p` is a subsingleton, but mapping it directly to SMT `Bool` would be
unsound for quantifiers: SMT would add a second value that Lean's type does not
have. All decision values and dependent functions ending in `Decidable` therefore
share a singleton SMT sort. The singleton axiom makes quantification exact.

The observable operation `decide p` is lowered separately to `p`. In particular,
applying a `DecidableEq α` and then observing its decision is exactly SMT equality;
the concrete decision-procedure implementation remains proof-irrelevant. -/

private def hasDecidableCodomain (ty : Expr) : MetaM Bool := do
  forallTelescopeReducing ty fun _ body => do
    let body ← whnf body
    return body.getAppFn.isConstOf ``Decidable

private def decisionEncoding : TranslateM (SSort × SMT.Term) := do
  let sortKey : StructuralKey := {
    tag := "decision-subsingleton-sort", name := ``Decidable
  }
  let sortName ← TranslateM.symbolForStructural sortKey "Decision"
  let sort := SSort.app (.symb sortName) #[]
  if !(← declaredSort sortName) then
    markSortDeclared sortName
    TranslateM.emitCommand (.declSort sortName 0)
  let valueKey : StructuralKey := {
    tag := "decision-subsingleton-value", name := ``Decidable
  }
  let valueName ← TranslateM.symbolForStructural valueKey "decision"
  if !(← declaredFun valueName) then
    markFunDeclared valueName
    TranslateM.emitCommand (.declFun valueName #[] sort)
    let x ← TranslateM.freshSymbol "decision_x"
    let xTerm := SMT.Term.const x
    let valueTerm := SMT.Term.const valueName
    TranslateM.emitCommand (.assert
      (.forallE #[(x, sort)] (smt| (= $xTerm $valueTerm))))
  return (sort, .const valueName)

/-- Every `Decidable p` family is represented by the same singleton sort. -/
@[crush_translate_sort]
def decidableSort : SortHandler := fun ctx => do
  let ty := mkAppN ctx.fn ctx.args
  unless ← hasDecidableCodomain ty do return none
  return some (← decisionEncoding).1

/-- A concrete decision or dependent decision procedure is the unique inhabitant
of the singleton decision sort. `Decidable` catches values and syntactic dependent
function codomains; `DecidableEq` catches terms whose inferred type retains the
named alias. -/
@[crush_lower_result Decidable, crush_lower_result DecidableEq]
def decidableValue : LoweringHandler := fun ctx => do
  let ty ← inferType (mkAppN ctx.fn ctx.args)
  unless ← hasDecidableCodomain ty do return none
  return some (← decisionEncoding).2

/-- Observing a decision returns the proposition it decides. -/
@[crush_lower decide]
def decideValue : LoweringHandler := fun ctx => do
  let #[p, _] := ctx.args | return none
  return some (← ctx.emitTerm p)

/-- `Int.natAbs x`, represented in the non-negative `Int` encoding used for `Nat`. -/
@[crush_lower Int.natAbs]
def intNatAbs : LoweringHandler := fun ctx => do
  let #[x] := ctx.args | return none
  let sx ← ctx.emitTerm x
  return some (smt| (ite (>= $sx 0) $sx (- $sx)))

/-- `Int.sign x`: `-1`, `0`, or `1` according to the arithmetic sign of `x`. -/
@[crush_lower Int.sign]
def intSign : LoweringHandler := fun ctx => do
  let #[x] := ctx.args | return none
  let sx ← ctx.emitTerm x
  return some (smt| (ite (> $sx 0) 1 (ite (= $sx 0) 0 (- 1))))

/-- Canonical integer/natural divisibility, using the exact remainder characterization
`a ∣ b ↔ b % a = 0`.

`intDivGuard` supplies Lean's value for `% 0`, making the characterization exact at
zero as well. Other carrier types and custom `Dvd` instances are declined. -/
@[crush_lower Dvd.dvd]
def dvd : LoweringHandler := fun ctx => do
  let #[carrier, _, a, b] := ctx.args | return none
  let carrier ← whnf carrier
  unless carrier.isConstOf ``Nat || carrier.isConstOf ``Int do return none
  let expected := mkConst (if carrier.isConstOf ``Nat then ``Nat.instDvd else ``Int.instDvd)
  unless ← ctx.hasExpectedInstance 1 expected do return none
  let sa ← ctx.emitTerm a
  let sb ← ctx.emitTerm b
  let remainder := intDivGuard "mod" sb sa
  return some (smt| (= $remainder 0))

/-! ## String operations

These are direct mappings to SMT's sequence-of-codepoints string theory. The
overloaded append form is claimed only for the canonical `String` instance;
custom dictionaries continue through the ordinary translator. Every handler
also declines when a sort extension has replaced the built-in SMT `String`
representation.

`String.replace` is deliberately absent: Lean inserts the replacement before
each codepoint when the pattern is empty, while SMT `str.replace_all` returns
the input unchanged. Character-pattern operations likewise require a dedicated
`Char` codepoint encoding; `Char` is currently an opaque sort. Lean's validated
string positions are UTF-8 byte offsets, while `String.take`/`drop` count
codepoints but return `String.Slice`; both positions and slices therefore need
a representation that relates them to the underlying SMT string. The numeric
parsers accept underscore separators, so `String.toNat?`/`String.toInt?` also
need more than direct symbol mappings.

String order is also deliberately absent. SMT-LIB 2.6's string alphabet stops
at `U+2FFFF`, while Lean strings admit Unicode scalar values through `U+10FFFF`.
Mapping Lean's lexicographic order to `str.<` would expose that smaller domain:
SMT can prove that every one-codepoint string is at most `U+2FFFF`, which is
false in Lean.
-/

private def usesStringTheory (ctx : TranslationCtx) : TranslateM Bool := do
  return (← ctx.emitSort (mkConst ``String)) == .app (.symb "String") #[]

/-- `String.length` counts Unicode codepoints, as does SMT `str.len`. -/
@[crush_lower String.length]
def stringLength : LoweringHandler := fun ctx => do
  let #[s] := ctx.args | return none
  unless ← usesStringTheory ctx do return none
  return some (smt| (str.len $(← ctx.emitTerm s)))

/-- Direct string append. -/
@[crush_lower String.append]
def stringAppend : LoweringHandler := fun ctx => do
  let #[a, b] := ctx.args | return none
  unless ← usesStringTheory ctx do return none
  return some (smt| (str.++ $(← ctx.emitTerm a) $(← ctx.emitTerm b)))

/-- `String.isEmpty s` is equality with the empty SMT string. -/
@[crush_lower String.isEmpty]
def stringIsEmpty : LoweringHandler := fun ctx => do
  let #[s] := ctx.args | return none
  unless ← usesStringTheory ctx do return none
  return some (smt| (= $(← ctx.emitTerm s) ""))

/-- String prefix testing. -/
@[crush_lower String.isPrefixOf]
def stringIsPrefixOf : LoweringHandler := fun ctx => do
  let #[pre, s] := ctx.args | return none
  unless ← usesStringTheory ctx do return none
  return some (smt| (str.prefixof $(← ctx.emitTerm pre) $(← ctx.emitTerm s)))

/-- Pattern-polymorphic prefix testing, restricted to the canonical `String` pattern. -/
@[crush_lower String.startsWith]
def stringStartsWith : LoweringHandler := fun ctx => do
  let #[patternTy, s, pre, _] := ctx.args | return none
  unless ← isStringType patternTy do return none
  unless ← usesStringTheory ctx do return none
  let expected := mkApp
    (mkConst ``String.Slice.Pattern.ForwardSliceSearcher.instForwardPattern_1) pre
  unless ← ctx.hasExpectedInstance 3 expected do return none
  return some (smt| (str.prefixof $(← ctx.emitTerm pre) $(← ctx.emitTerm s)))

/-- Pattern-polymorphic suffix testing, restricted to the canonical `String` pattern. -/
@[crush_lower String.endsWith]
def stringEndsWith : LoweringHandler := fun ctx => do
  let #[patternTy, s, suffix, _] := ctx.args | return none
  unless ← isStringType patternTy do return none
  unless ← usesStringTheory ctx do return none
  let expected := mkApp
    (mkConst ``String.Slice.Pattern.BackwardSliceSearcher.instBackwardPattern_1) suffix
  unless ← ctx.hasExpectedInstance 3 expected do return none
  return some (smt| (str.suffixof $(← ctx.emitTerm suffix) $(← ctx.emitTerm s)))

/-- Pattern search (`contains`/`any`), restricted to Lean's canonical `String`
searcher and iterator instances. -/
@[crush_lower String.contains, crush_lower String.any]
def stringContains : LoweringHandler := fun ctx => do
  let #[patternTy, _, _, _, s, pattern, _] := ctx.args | return none
  unless ← isStringType patternTy do return none
  unless ← usesStringTheory ctx do return none
  unless ← ctx.hasExpectedInstance 2
    (mkConst ``String.Slice.Pattern.ForwardSliceSearcher.instIteratorIdSearchStep) do
    return none
  unless ← ctx.hasExpectedInstance 3
    (mkConst ``String.Slice.Pattern.ForwardSliceSearcher.instIteratorLoopIdSearchStep [.zero]) do
    return none
  let expectedSearcher := mkApp
    (mkConst ``String.Slice.Pattern.ForwardSliceSearcher.instToForwardSearcher_1) pattern
  unless ← ctx.hasExpectedInstance 6 expectedSearcher do return none
  return some (smt| (str.contains $(← ctx.emitTerm s) $(← ctx.emitTerm pattern)))

/-- The notation-level `String` append, after checking its overloaded instance. -/
@[crush_lower HAppend.hAppend]
def stringHAppend : LoweringHandler := fun ctx => do
  let #[leftTy, rightTy, resultTy, _, a, b] := ctx.args | return none
  unless ← isStringType leftTy do return none
  unless ← isStringType rightTy do return none
  unless ← isStringType resultTy do return none
  unless ← usesStringTheory ctx do return none
  let expected := mkApp2 (mkConst ``instHAppendOfAppend [.zero])
    (mkConst ``String) (mkConst ``instAppendString)
  unless ← ctx.hasExpectedInstance 3 expected do return none
  return some (smt| (str.++ $(← ctx.emitTerm a) $(← ctx.emitTerm b)))

/-! ## Finite Array operations

These use the same public `withFiniteArray` view available to downstream
`@[crush_lower]` handlers. The helper returns `none` when a custom sort handler
has replaced Crush's finite Array representation.
-/

private def optionTerms (elem : Expr) (value : SMT.Term) :
    TranslateM (SMT.Term × SMT.Term) := do
  let optionSort ← declareDatatype ``Option #[elem]
  let noneCtor ← reserveCtorSymbol optionSort ``Option.none
  let someCtor ← reserveCtorSymbol optionSort ``Option.some
  let noneTerm := SMT.Term.const noneCtor
  let someTerm := SMT.Term.app (.symb someCtor) #[value]
  return (noneTerm, someTerm)

private def guardedArrayStore (ctx : TranslationCtx)
    (elem arr idx value : Expr) : TranslateM (Option SMT.Term) := do
  let sidx ← ctx.emitTerm idx
  let svalue ← ctx.emitTerm value
  withFiniteArray ctx elem arr fun view => do
    let stored := (smt| (store $(view.data) $sidx $svalue))
    let updated := view.mkValue view.length stored
    return (smt| (ite (< $sidx $(view.length)) $updated $(view.value)))

@[crush_lower Array.replicate]
def arrayReplicate : LoweringHandler := fun ctx => do
  let #[elem, length, value] := ctx.args | return none
  let arrayTy ← inferType (mkAppN ctx.fn ctx.args)
  let slength ← ctx.emitTerm length
  let svalue ← ctx.emitTerm value
  withFiniteArrayType ctx arrayTy elem fun encoding => do
    let elemSort ← ctx.emitSort elem
    let intSort := SSort.app (.symb "Int") #[]
    let dataSort := SSort.app (.symb "Array") #[intSort, elemSort]
    let key : StructuralKey := {
      tag := "array-replicate-data", name := ``Array.replicate, typeExprs := #[elem]
    }
    let dataFn ← TranslateM.symbolForStructural key "array_replicate"
    if !(← declaredFun dataFn) then
      markFunDeclared dataFn
      TranslateM.emitCommand (.declFun dataFn #[intSort, elemSort] dataSort)
      let nName ← TranslateM.freshSymbol "n"
      let valueName ← TranslateM.freshSymbol "value"
      let iName ← TranslateM.freshSymbol "i"
      let n := SMT.Term.const nName
      let v := SMT.Term.const valueName
      let i := SMT.Term.const iName
      let data := SMT.Term.app (.symb dataFn) #[n, v]
      let sentinel := SMT.Term.const encoding.sentinel
      let rhs := (smt| (ite (and (>= $i 0) (< $i $n)) $v $sentinel))
      TranslateM.emitCommand (.assert (.forallE
        #[(nName, intSort), (valueName, elemSort), (iName, intSort)]
        (smt| (= (select $data $i) $rhs))))
    let data := SMT.Term.app (.symb dataFn) #[slength, svalue]
    return SMT.Term.app (.symb encoding.ctor) #[slength, data]

@[crush_lower Array.size]
def arraySize : LoweringHandler := fun ctx => do
  let #[elem, arr] := ctx.args | return none
  withFiniteArray ctx elem arr fun view => return view.length

@[crush_lower GetElem.getElem]
def arrayGetElem : LoweringHandler := fun ctx => do
  let #[coll, idxTy, elem, _, _, arr, idx, _] := ctx.args | return none
  let some arrayElem ← finiteArrayElem? coll | return none
  unless (← whnf idxTy).isConstOf ``Nat do return none
  unless ← isDefEqReadOnly elem arrayElem do return none
  unless ctx.hasInstanceHead 4 ``Array.instGetElemNatLtSize do return none
  let sidx ← ctx.emitTerm idx
  withFiniteArray ctx arrayElem arr fun view =>
    return (smt| (select $(view.data) $sidx))

@[crush_lower GetElem?.getElem!]
def arrayGetElemBang : LoweringHandler := fun ctx => do
  let #[coll, idxTy, elem, _, _, inhabited, arr, idx] := ctx.args | return none
  let some arrayElem ← finiteArrayElem? coll | return none
  unless (← whnf idxTy).isConstOf ``Nat do return none
  unless ← isDefEqReadOnly elem arrayElem do return none
  unless ctx.hasInstanceHead 4 ``Array.instGetElem?NatLtSize do return none
  let sidx ← ctx.emitTerm idx
  let defaultFn := mkConst ``default [← getLevel elem]
  let sdefault ← ctx.emitTerm (mkApp2 defaultFn elem inhabited)
  withFiniteArray ctx arrayElem arr fun view =>
    return (smt| (ite (< $sidx $(view.length))
      (select $(view.data) $sidx) $sdefault))

@[crush_lower GetElem?.getElem?]
def arrayGetElemOpt : LoweringHandler := fun ctx => do
  let #[coll, idxTy, elem, _, _, arr, idx] := ctx.args | return none
  let some arrayElem ← finiteArrayElem? coll | return none
  unless (← whnf idxTy).isConstOf ``Nat do return none
  unless ← isDefEqReadOnly elem arrayElem do return none
  unless ctx.hasInstanceHead 4 ``Array.instGetElem?NatLtSize do return none
  let sidx ← ctx.emitTerm idx
  withFiniteArray ctx arrayElem arr fun view => do
    let value := (smt| (select $(view.data) $sidx))
    let (noneTerm, someTerm) ← optionTerms arrayElem value
    return (smt| (ite (< $sidx $(view.length)) $someTerm $noneTerm))

@[crush_lower Array.set]
def arraySet : LoweringHandler := fun ctx => do
  let #[elem, arr, idx, value, _] := ctx.args | return none
  guardedArrayStore ctx elem arr idx value

@[crush_lower Array.setIfInBounds]
def arraySetIfInBounds : LoweringHandler := fun ctx => do
  let #[elem, arr, idx, value] := ctx.args | return none
  guardedArrayStore ctx elem arr idx value

@[crush_lower Array.set!]
def arraySetBang : LoweringHandler := fun ctx => do
  let #[elem, arr, idx, value] := ctx.args | return none
  guardedArrayStore ctx elem arr idx value

@[crush_lower Array.push]
def arrayPush : LoweringHandler := fun ctx => do
  let #[elem, arr, value] := ctx.args | return none
  let svalue ← ctx.emitTerm value
  withFiniteArray ctx elem arr fun view => do
    let stored := (smt| (store $(view.data) $(view.length) $svalue))
    return view.mkValue (smt| (+ $(view.length) 1)) stored

@[crush_lower Array.pop]
def arrayPop : LoweringHandler := fun ctx => do
  let #[elem, arr] := ctx.args | return none
  withFiniteArray ctx elem arr fun view => do
    let newLen := (smt| (ite (> $(view.length) 0) (- $(view.length) 1) 0))
    let sentinel := SMT.Term.const view.encoding.sentinel
    let cleaned := (smt| (ite (> $(view.length) 0)
      (store $(view.data) $newLen $sentinel) $(view.data)))
    return view.mkValue newLen cleaned

private def arraySwapTerm (ctx : TranslationCtx)
    (elem arr i j : Expr) : TranslateM (Option SMT.Term) := do
  let si ← ctx.emitTerm i
  let sj ← ctx.emitTerm j
  withFiniteArray ctx elem arr fun view => do
    let vi := (smt| (select $(view.data) $si))
    let vj := (smt| (select $(view.data) $sj))
    let swapped := (smt| (store (store $(view.data) $si $vj) $sj $vi))
    let updated := view.mkValue view.length swapped
    return (smt| (ite (and (< $si $(view.length)) (< $sj $(view.length)))
      $updated $(view.value)))

@[crush_lower Array.swap]
def arraySwap : LoweringHandler := fun ctx => do
  let #[elem, arr, i, j, _, _] := ctx.args | return none
  arraySwapTerm ctx elem arr i j

@[crush_lower Array.swapIfInBounds]
def arraySwapIfInBounds : LoweringHandler := fun ctx => do
  let #[elem, arr, i, j] := ctx.args | return none
  arraySwapTerm ctx elem arr i j

@[crush_lower Array.isEmpty]
def arrayIsEmpty : LoweringHandler := fun ctx => do
  let #[elem, arr] := ctx.args | return none
  withFiniteArray ctx elem arr fun view =>
    return (smt| (= $(view.length) 0))

@[crush_lower Array.back!]
def arrayBackBang : LoweringHandler := fun ctx => do
  let #[elem, inhabited, arr] := ctx.args | return none
  let defaultFn := mkConst ``default [← getLevel elem]
  let sdefault ← ctx.emitTerm (mkApp2 defaultFn elem inhabited)
  withFiniteArray ctx elem arr fun view =>
    return (smt| (ite (> $(view.length) 0)
      (select $(view.data) (- $(view.length) 1)) $sdefault))

@[crush_lower Array.back?]
def arrayBackOpt : LoweringHandler := fun ctx => do
  let #[elem, arr] := ctx.args | return none
  withFiniteArray ctx elem arr fun view => do
    let value := (smt| (select $(view.data) (- $(view.length) 1)))
    let (noneTerm, someTerm) ← optionTerms elem value
    return (smt| (ite (> $(view.length) 0) $someTerm $noneTerm))

end Crush.DefaultLowerings
