import Crush.Metatheory.HO.Core

/-!
# First-order target sorts and symbol declarations

This is the proof-facing target of Crush's defunctionalization pass.  Unlike the
higher-order source language, the target has neither arrows, lambdas, nor a
distinguished application constructor.  Function values inhabit an opaque `.fn`
sort, and application and closure construction are ordinary first-order symbol
declarations.

The declarations deliberately follow the emitted SMT encoding in
`Crush.Translation.HOEncoding` and `Crush.Translation.Translate`:

* every complete source arrow type has its own function-value sort;
* its generated `app` symbol takes the function value followed by the *fully
  flattened* source arguments;
* a closure constructor takes its captured values and returns the function-value
  sort for the lambda's complete arrow type.

Target *terms* over these declarations are `FO.FamilyTerm` (`FO/Family.lean`),
indexed by an abstract symbol family rather than by positions in a finite
signature.  Symbol names, the finite allocation, and Lean expression reification
remain outside this development.
-/

namespace Crush.Metatheory.FO

/-- First-order target sorts.  `fn domain codomain` is the opaque SMT sort used to
represent values of the complete source type `domain → codomain`.  Retaining that
source arrow identifies distinct arrow sorts without admitting arrows into FO. -/
inductive FOSort where
  | bool : FOSort
  | base : BaseSort → FOSort
  | fn : Ty → Ty → FOSort
  deriving BEq, ReflBEq, LawfulBEq, DecidableEq, Hashable, Repr

namespace FOSort

/-- Erase a source type to its first-order representation. -/
@[reducible] def ofTy : Ty → FOSort
  | .bool => .bool
  | .base baseSort => .base baseSort
  | .arrow domain codomain => .fn domain codomain

end FOSort

/-- Flatten all leading arrows in a source type.  This mirrors the Crush translator
`arrowShape?`, but dependency cannot arise in the core language. -/
@[reducible] def flattenArrow : Ty → List Ty × Ty
  | .arrow domain codomain =>
      let (domains, result) := flattenArrow codomain
      (domain :: domains, result)
  | result => ([], result)

/-- A first-order symbol declaration with a fixed argument telescope and result
sort.  Constants are precisely declarations with no arguments. -/
structure SymbolDecl where
  args : List FOSort
  result : FOSort
  deriving BEq, DecidableEq, Repr

/-- A typed de Bruijn reference to a target variable. -/
inductive Var : (context : List FOSort) → FOSort → Type where
  | here {sort : FOSort} {context : List FOSort} : Var (sort :: context) sort
  | there {sort head : FOSort} {context : List FOSort} :
      Var context sort → Var (head :: context) sort
  deriving Repr

abbrev Context := List FOSort

/-! ## Declarations generated by the translator's defunctionalization scheme -/

/-- The opaque target sort associated with a source arrow. -/
def arrowSort (domain codomain : Ty) : FOSort := .fn domain codomain

/-- The fully flattened declaration of the generated application symbol.

For `σ₁ → σ₂ → τ`, this has arguments
`[Fn_(σ₁→σ₂→τ), ⟦σ₁⟧, ⟦σ₂⟧]` and result `⟦τ⟧`, exactly as the Crush translator does. -/
def appDecl (domain codomain : Ty) : SymbolDecl :=
  let arrow := Ty.arrow domain codomain
  let (domains, result) := flattenArrow arrow
  { args := arrowSort domain codomain :: domains.map FOSort.ofTy
    result := FOSort.ofTy result }

/-- The declaration of a closure constructor with the given captured source
types and complete lambda arrow type. -/
@[reducible] def closureDecl (captures : List Ty) (domain codomain : Ty) : SymbolDecl :=
  { args := captures.map FOSort.ofTy
    result := arrowSort domain codomain }

@[simp] theorem flattenArrow_arrow (domain codomain : Ty) :
    flattenArrow (.arrow domain codomain) =
      (domain :: (flattenArrow codomain).1, (flattenArrow codomain).2) := rfl

@[simp] theorem appDecl_args (domain codomain : Ty) :
    (appDecl domain codomain).args =
      arrowSort domain codomain ::
        (domain :: (flattenArrow codomain).1).map FOSort.ofTy := rfl

@[simp] theorem appDecl_result (domain codomain : Ty) :
    (appDecl domain codomain).result = FOSort.ofTy (flattenArrow codomain).2 := rfl

@[simp] theorem closureDecl_args (captures : List Ty) (domain codomain : Ty) :
    (closureDecl captures domain codomain).args = captures.map FOSort.ofTy := rfl

@[simp] theorem closureDecl_result (captures : List Ty) (domain codomain : Ty) :
    (closureDecl captures domain codomain).result = arrowSort domain codomain := rfl

end Crush.Metatheory.FO
