import Lean

open Lean Meta

namespace Crush

/-- Environment boundary used to identify declarations generated by proof automation. -/
structure KernelCheckSnapshot where
  private env : Environment

def KernelCheckSnapshot.capture : CoreM KernelCheckSnapshot :=
  return { env := ← getEnv }

private def throwKernelFailure {α} (label : String) (ex : Kernel.Exception) : MetaM α := do
  throwError "crush: {label} failed kernel validation:\n{ex.toMessageData (← getOptions)}"

/-- Check `proof` against `expected`, rather than merely inferring some type for `proof`. -/
private def kernelCheckExpected (env : Environment) (lctx : LocalContext)
    (expected proof : Expr) (label : String) : MetaM Unit := do
  let expectedType ←
    match Kernel.check env lctx expected with
    | .ok type => pure type
    | .error ex => throwKernelFailure s!"{label} type" ex
  let .sort level := expectedType.consumeMData
    | throwError "crush: {label} has a kernel-inferred type that is not a sort"
  let wrapped := mkApp2 (mkConst ``id [level]) expected proof
  match Kernel.check env lctx wrapped with
  | .ok _ => return
  | .error ex => throwKernelFailure label ex

private def ensureComplete (label : String) (e : Expr) : MetaM Unit := do
  if e.hasSorry then
    throwError "crush: {label} contains `sorry`"
  if e.hasMVar then
    throwError "crush: {label} contains unresolved metavariables"

/-- Collect the local declarations needed to close `exprs`, without scanning unrelated
entries in the ambient context. Visible let values contribute dependencies; nondependent
lets are generalized and therefore contribute only their types. -/
def collectProofParams (exprs : Array Expr) : MetaM (Array Expr) := do
  let lctx ← getLCtx
  let mut used : CollectFVars.State := {}
  for expr in exprs do
    used := Lean.collectFVars used (← instantiateMVars expr)
  let mut cursor := 0
  while cursor < used.fvarIds.size do
    let fvarId := used.fvarIds[cursor]!
    cursor := cursor + 1
    if let some decl := lctx.find? fvarId then
      used := Lean.collectFVars used (← instantiateMVars decl.type)
      if let some value := decl.value? then
        used := Lean.collectFVars used (← instantiateMVars value)
  let mut indexed : Array (Nat × Expr) := #[]
  let mut retained : FVarIdSet := {}
  for fvarId in used.fvarIds do
    if retained.contains fvarId then continue
    if let some decl := lctx.find? fvarId then
      retained := retained.insert fvarId
      indexed := indexed.push (decl.index, mkFVar fvarId)
  return (indexed.qsort (fun left right => left.1 < right.1)).map (·.2)

/-- Validate a generated declaration and every generated declaration it references. -/
private partial def checkGeneratedDeclaration (baseline current : Environment) (name : Name)
    (checked visiting : Std.HashSet Name) : MetaM (Std.HashSet Name) := do
  if baseline.contains name || checked.contains name then
    return checked
  if visiting.contains name then
    throwError "crush: generated proof declarations contain a cycle through `{name}`"
  let some info := current.find? name
    | throwError "crush: reconstructed proof references unknown generated declaration `{name}`"
  let some value := info.value? (allowOpaque := true)
    | throwError "crush: reconstructed proof references unchecked generated declaration `{name}`"
  let type ← instantiateMVars info.type
  let value ← instantiateMVars value
  ensureComplete s!"generated declaration `{name}` type" type
  ensureComplete s!"generated declaration `{name}` value" value
  let visiting := visiting.insert name
  let mut checked := checked
  for dependency in type.getUsedConstants do
    checked ← checkGeneratedDeclaration baseline current dependency checked visiting
  for dependency in value.getUsedConstants do
    checked ← checkGeneratedDeclaration baseline current dependency checked visiting
  kernelCheckExpected current {} type value s!"generated declaration `{name}`"
  return checked.insert name

/-- Kernel-check a complete proof candidate using a dependency-closed list of local
parameters, together with any declarations generated while building it. -/
def kernelCheckProofWithParams (snapshot : KernelCheckSnapshot) (params : Array Expr)
    (expected proof : Expr) : MetaM Expr := do
  let expected ← instantiateMVars expected
  let proof ← instantiateMVars proof
  let closedExpected ← instantiateMVars (← mkForallFVars params expected)
  let closedProof ← instantiateMVars (← mkLambdaFVars params proof)
  ensureComplete "reconstructed goal type" closedExpected
  ensureComplete "reconstructed proof" closedProof
  let current ← getEnv
  let mut checked : Std.HashSet Name := {}
  for name in closedExpected.getUsedConstants do
    checked ← checkGeneratedDeclaration snapshot.env current name checked {}
  for name in closedProof.getUsedConstants do
    checked ← checkGeneratedDeclaration snapshot.env current name checked {}
  kernelCheckExpected current {} closedExpected closedProof "reconstructed proof"
  return proof

/-- Kernel-check a complete proof candidate and any declarations generated while building it. -/
def kernelCheckProof (snapshot : KernelCheckSnapshot) (expected proof : Expr) : MetaM Expr := do
  let params ← collectProofParams #[expected, proof]
  kernelCheckProofWithParams snapshot params expected proof

end Crush
