import Lean

open Lean Meta

namespace Crush

/-- Environment boundary used to identify declarations generated by proof automation. -/
structure KernelCheckSnapshot where
  private env : Environment

def KernelCheckSnapshot.capture : CoreM KernelCheckSnapshot :=
  return { env := ← getEnv }

private def throwKernelFailure {α} (label : String) (ex : Kernel.Exception) : MetaM α := do
  throwError "crush: {label} failed kernel validation:\n{ex.toMessageData (← getOptions)}"

/-- Check `proof` against `expected`, rather than merely inferring some type for `proof`. -/
private def kernelCheckExpected (env : Environment) (lctx : LocalContext)
    (expected proof : Expr) (label : String) : MetaM Unit := do
  let expectedType ←
    match Kernel.check env lctx expected with
    | .ok type => pure type
    | .error ex => throwKernelFailure s!"{label} type" ex
  let .sort level := expectedType.consumeMData
    | throwError "crush: {label} has a kernel-inferred type that is not a sort"
  let wrapped := mkApp2 (mkConst ``id [level]) expected proof
  match Kernel.check env lctx wrapped with
  | .ok _ => return
  | .error ex => throwKernelFailure label ex

private def ensureComplete (label : String) (e : Expr) : MetaM Unit := do
  if e.hasSorry then
    throwError "crush: {label} contains `sorry`"
  if e.hasMVar then
    throwError "crush: {label} contains unresolved metavariables"

/-- Validate a generated declaration and every generated declaration it references. -/
private partial def checkGeneratedDeclaration (baseline current : Environment) (name : Name)
    (checked visiting : Std.HashSet Name) : MetaM (Std.HashSet Name) := do
  if baseline.contains name || checked.contains name then
    return checked
  if visiting.contains name then
    throwError "crush: generated proof declarations contain a cycle through `{name}`"
  let some info := current.find? name
    | throwError "crush: reconstructed proof references unknown generated declaration `{name}`"
  let some value := info.value? (allowOpaque := true)
    | throwError "crush: reconstructed proof references unchecked generated declaration `{name}`"
  let type ← instantiateMVars info.type
  let value ← instantiateMVars value
  ensureComplete s!"generated declaration `{name}` type" type
  ensureComplete s!"generated declaration `{name}` value" value
  let visiting := visiting.insert name
  let mut checked := checked
  for dependency in type.getUsedConstants do
    checked ← checkGeneratedDeclaration baseline current dependency checked visiting
  for dependency in value.getUsedConstants do
    checked ← checkGeneratedDeclaration baseline current dependency checked visiting
  kernelCheckExpected current {} type value s!"generated declaration `{name}`"
  return checked.insert name

/-- Kernel-check a complete proof candidate and any declarations generated while building it. -/
def kernelCheckProof (snapshot : KernelCheckSnapshot) (expected proof : Expr) : MetaM Expr := do
  let expected ← instantiateMVars expected
  let proof ← instantiateMVars proof
  let used := Lean.collectFVars (Lean.collectFVars {} expected) proof
  let (_, _, params) ← Meta.removeUnused (← getLCtx).getFVars used
  let closedExpected ← instantiateMVars (← mkForallFVars params expected)
  let closedProof ← instantiateMVars (← mkLambdaFVars params proof)
  ensureComplete "reconstructed goal type" closedExpected
  ensureComplete "reconstructed proof" closedProof
  let current ← getEnv
  let mut checked : Std.HashSet Name := {}
  for name in closedExpected.getUsedConstants do
    checked ← checkGeneratedDeclaration snapshot.env current name checked {}
  for name in closedProof.getUsedConstants do
    checked ← checkGeneratedDeclaration snapshot.env current name checked {}
  kernelCheckExpected current {} closedExpected closedProof "reconstructed proof"
  return proof

end Crush
