import Crush.Metatheory.Defunctionalization.FlattenedApplication
import Crush.Metatheory.Defunctionalization.ModelExtension
import Crush.Metatheory.Guarded.Encoding

/-!
# Semantic contracts for translation hooks

An extension that maps a source constant to a target symbol must preserve the
logical relation after every argument in the source constant's flattened arrow
telescope. `FlattenedHookRel` states exactly that condition, independently of
symbol names and metaprogram execution.

The live unrestricted attributes remain useful but are tagged
`HandlerTrust.trustedBoundary`. A certified registration path must provide an
inhabitant of the non-vacuous `CanonicalTermHookCertificate` below (or the
guarded sort contract) and prove that its executable handler emits the
represented declaration.
-/

namespace Crush.Metatheory

open Lean

/-- An arbitrary type-indexed relation between source values and target values.
For defunctionalization this is instantiated by the source/target logical
relation; guarded encodings instantiate it with their representation relation. -/
abbrev HookValueRelation (sourceBase : BaseSort → Type)
    (targetCarriers : FO.Carriers) :=
  (ty : Ty) → ty.Denote sourceBase →
    (FO.FOSort.ofTy ty).Denote targetCarriers → Prop

/-- Relation required of a fully flattened target symbol implementing a source
value. Each arrow consumes related source/target arguments; the final result
must be related at its non-arrow result type. Its target type is definitionally
the declaration generated by `Defunctionalization.sourceDecl`. -/
@[reducible] def FlattenedHookRel {sourceBase : BaseSort → Type}
    {targetCarriers : FO.Carriers}
    (valueRel : HookValueRelation sourceBase targetCarriers) :
    (ty : Ty) → ty.Denote sourceBase →
      FO.SymbolDenote targetCarriers
        (Defunctionalization.sourceDecl ty).args
        (Defunctionalization.sourceDecl ty).result → Prop
  | .bool, sourceValue, targetValue =>
      valueRel .bool sourceValue targetValue
  | .base sort, sourceValue, targetValue =>
      valueRel (.base sort) sourceValue targetValue
  | .arrow domain codomain, sourceFn, targetFn =>
      ∀ sourceArgument targetArgument,
        valueRel domain sourceArgument targetArgument →
        FlattenedHookRel valueRel codomain
          (sourceFn sourceArgument) (targetFn targetArgument)

/-- Semantic certificate for a term/built-in hook at one source type. -/
structure TermHookCertificate {sourceBase : BaseSort → Type}
    {targetCarriers : FO.Carriers}
    (valueRel : HookValueRelation sourceBase targetCarriers) (ty : Ty) where
  sourceValue : ty.Denote sourceBase
  targetValue : FO.SymbolDenote targetCarriers
    (Defunctionalization.sourceDecl ty).args
    (Defunctionalization.sourceDecl ty).result
  preserves : FlattenedHookRel valueRel ty sourceValue targetValue

/-- Universe-independent package stored by the live certified-hook registry.
Unpacking it recovers the exact source type, source/target models, logical
relation, and preservation proof; registration therefore cannot manufacture a
`certified` tag from a bare theorem name. -/
inductive SomeTermHookCertificate where
  | pack {sourceBase : BaseSort → Type} {targetCarriers : FO.Carriers}
      {valueRel : HookValueRelation sourceBase targetCarriers} {ty : Ty}
      (certificate : TermHookCertificate valueRel ty) : SomeTermHookCertificate

namespace SomeTermHookCertificate

def arity : SomeTermHookCertificate → Nat
  | .pack (ty := ty) _ => (Defunctionalization.sourceDecl ty).args.length

/-- Elimination principle used by audits that only need to know a genuine
semantic preservation witness was retained. -/
theorem hasPreservation (certificate : SomeTermHookCertificate) :
    ∃ (sourceBase : BaseSort → Type) (targetCarriers : FO.Carriers)
      (valueRel : HookValueRelation sourceBase targetCarriers) (ty : Ty)
      (sourceValue : ty.Denote sourceBase)
      (targetValue : FO.SymbolDenote targetCarriers
        (Defunctionalization.sourceDecl ty).args
        (Defunctionalization.sourceDecl ty).result),
      FlattenedHookRel valueRel ty sourceValue targetValue := by
  cases certificate with
  | pack semantic =>
      exact ⟨_, _, _, _, semantic.sourceValue, semantic.targetValue,
        semantic.preserves⟩

end SomeTermHookCertificate

namespace TermHookCertificate

theorem preserves_bool {sourceBase : BaseSort → Type}
    {targetCarriers : FO.Carriers}
    {valueRel : HookValueRelation sourceBase targetCarriers}
    (certificate : TermHookCertificate valueRel .bool) :
    valueRel .bool certificate.sourceValue certificate.targetValue :=
  certificate.preserves

theorem preserves_base {sourceBase : BaseSort → Type}
    {targetCarriers : FO.Carriers}
    {valueRel : HookValueRelation sourceBase targetCarriers}
    (sort : BaseSort) (certificate : TermHookCertificate valueRel (.base sort)) :
    valueRel (.base sort) certificate.sourceValue certificate.targetValue :=
  certificate.preserves

/-- Certified application consumes one related argument and produces the
certificate obligation for the residual result type. -/
def apply {sourceBase : BaseSort → Type} {targetCarriers : FO.Carriers}
    {valueRel : HookValueRelation sourceBase targetCarriers}
    {domain codomain : Ty}
    (certificate : TermHookCertificate valueRel (.arrow domain codomain))
    (sourceArgument : domain.Denote sourceBase)
    (targetArgument : (FO.FOSort.ofTy domain).Denote targetCarriers)
    (argumentRelated : valueRel domain sourceArgument targetArgument) :
    TermHookCertificate valueRel codomain where
  sourceValue := certificate.sourceValue sourceArgument
  targetValue := certificate.targetValue targetArgument
  preserves := certificate.preserves sourceArgument targetArgument argumentRelated

end TermHookCertificate

/-! ## Canonical certificates suitable for a live trust boundary

The generic contract above is useful compositionally but must not itself drive a
`certified` registry: existentially choosing `valueRel := fun _ _ _ => True`
would make it vacuous. The following contract fixes the target to the canonical
model extension and the relation to Crush's actual `ValueRel`, with equality on
opaque base carriers, and quantifies over every source model. -/

/-- The exact logical relation used by the model-extension proof. -/
abbrev CanonicalHookValueRelation {signature : Signature}
    (source : Model signature) : HookValueRelation source.Base
      (Defunctionalization.canonicalModel source).carriers :=
  Defunctionalization.ValueRel source
    (Defunctionalization.canonicalModel source)
    (fun _ sourceValue targetValue => sourceValue = targetValue)

/-- A flattened implementation valid in every source model under Crush's
canonical defunctionalization relation. Unlike `TermHookCertificate`, the model
and relation cannot be selected by the certificate author. -/
structure CanonicalTermHookCertificate (signature : Signature) (ty : Ty) where
  sourceValue : (source : Model signature) → ty.Denote source.Base
  targetValue : (source : Model signature) →
    FO.SymbolDenote (Defunctionalization.canonicalModel source).carriers
      (Defunctionalization.sourceDecl ty).args
      (Defunctionalization.sourceDecl ty).result
  preserves : (source : Model signature) →
    FlattenedHookRel (CanonicalHookValueRelation source) ty
      (sourceValue source) (targetValue source)

namespace CanonicalTermHookCertificate

/-- Applying a universally certified hook to a canonically related argument
preserves the universal certificate for its residual function result. -/
def apply {signature : Signature} {domain codomain : Ty}
    (certificate : CanonicalTermHookCertificate signature (.arrow domain codomain))
    (sourceArgument : (source : Model signature) → domain.Denote source.Base)
    (targetArgument : (source : Model signature) →
      (FO.FOSort.ofTy domain).Denote
        (Defunctionalization.canonicalModel source).carriers)
    (argumentRelated : (source : Model signature) →
      CanonicalHookValueRelation source domain
        (sourceArgument source) (targetArgument source)) :
    CanonicalTermHookCertificate signature codomain where
  sourceValue := fun source => certificate.sourceValue source (sourceArgument source)
  targetValue := fun source => certificate.targetValue source (targetArgument source)
  preserves := fun source => certificate.preserves source
    (sourceArgument source) (targetArgument source) (argumentRelated source)

end CanonicalTermHookCertificate

/-- The production flattened interpretation of any source value is related to
that value by the canonical model-extension relation. This is the semantic fact
a mechanically emitted direct-symbol hook must refine. -/
theorem flattenedDenote_canonical_related {signature : Signature}
    (source : Model signature) :
    (ty : Ty) → (value : ty.Denote source.Base) →
      FlattenedHookRel (CanonicalHookValueRelation source) ty value
        (Defunctionalization.Flattened.flattenedDenote source ty value) := by
  intro ty
  induction ty with
  | bool =>
      intro value
      exact Iff.rfl
  | base sort =>
      intro value
      rfl
  | arrow domain codomain domainIH codomainIH =>
      intro fn sourceArgument targetArgument argumentRelated
      have argumentEq :=
        (Defunctionalization.canonical_valueRel_iff source domain _ _).1
          argumentRelated
      rw [argumentEq]
      exact codomainIH (fn (Defunctionalization.fromCanonical source domain targetArgument))

/-- Canonical semantic certificate tied to one actual intrinsic source constant.
Indexing by `constant` prevents a live registry from presenting a theorem about
an unrelated value at the same type. -/
structure CanonicalConstantHookCertificate {signature : Signature} {ty : Ty}
    (constant : Const signature ty) where
  targetValue : (source : Model signature) →
    FO.SymbolDenote (Defunctionalization.canonicalModel source).carriers
      (Defunctionalization.sourceDecl ty).args
      (Defunctionalization.sourceDecl ty).result
  preserves : (source : Model signature) →
    FlattenedHookRel (CanonicalHookValueRelation source) ty
      (source.const constant) (targetValue source)

/-- Every source constant has a canonical production implementation. Certified
built-ins may replace `targetValue` only by proving the same indexed contract. -/
def CanonicalConstantHookCertificate.production {signature : Signature} {ty : Ty}
    (constant : Const signature ty) : CanonicalConstantHookCertificate constant where
  targetValue := fun source =>
    Defunctionalization.Flattened.flattenedDenote source ty (source.const constant)
  preserves := fun source =>
    flattenedDenote_canonical_related source ty (source.const constant)

/-! ## Certified built-in example: Boolean negation

An arbitrary `Lean.Name` has no kernel-level denotation, so it cannot honestly
index a semantic certificate.  Built-ins avoid that gap by fixing both endpoints
in executable code: the only mapping using this theorem maps Lean's `Not` to the
logical `not` constructor of the verified SMT fragment. -/

namespace BuiltinHooks

def notSemantic : CanonicalTermHookCertificate [] (.arrow .bool .bool) where
  sourceValue := fun _ => Not
  targetValue := fun _ => Not
  preserves := by
    intro source sourceArgument targetArgument related
    exact not_congr related

theorem not_preserves (source : Model []) (sourceValue targetValue : Prop)
    (related : sourceValue ↔ targetValue) :
    ¬sourceValue ↔ ¬targetValue :=
  notSemantic.preserves source sourceValue targetValue related

end BuiltinHooks

set_option linter.checkUnivs false in
/-- Sort hooks use the guarded representation contract already proved in Goal 8.
This alias makes the requirement explicit at the extension boundary. -/
abbrev SortHookCertificate := Guarded.Encoding

end Crush.Metatheory
