import Crush.Metatheory.Reification.Witness
import Crush.Metatheory.VCG.Status

/-!
# Proved verification-condition generation

This is the total proof-facing route after successful Lean-to-HO reification.
It runs the intrinsic flattened translation and the pure FO-to-SMT encoder. The
resulting status retains an exact representation theorem by construction.
-/

namespace Crush.Metatheory.VCG

open Defunctionalization.Flattened
open scoped Crush.Metatheory

/-- The SMT encoder's complete translated result is the flattened complete
target theory for the same intrinsic source sentence. -/
theorem completeTheory_translate {signature : Signature}
    (source : Sentence signature) :
    SMT.completeTheory 𝓕⟦source⟧ = translatedTheory source := rfl

/-- Exact concrete commands generated by the total proved VCG route. -/
def commands {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) : Array Crush.SMT.Command :=
  SMT.encode encoding 𝓕⟦source⟧

/-- The proved VCG command sequence represents the complete flattened theory. -/
theorem commands_represents {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) :
    SMT.TheoryRepresentation encoding (translatedTheory source)
      (commands encoding source) := by
  rw [← completeTheory_translate source]
  exact SMT.encode_translation encoding 𝓕⟦source⟧

/-- Classify total intrinsic VCG as proved and retain its representation. -/
def generate {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) : TranslationStatus encoding :=
  .proved source (commands encoding source) (commands_represents encoding source)

theorem generate_proves {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) :
    (generate encoding source).Proves source := by
  exact ⟨commands encoding source, commands_represents encoding source, rfl⟩

/-- Unsatisfiability of commands from total proved VCG reflects to the
intrinsic HO sentence. -/
theorem commands_unsat_implies_source_unsat {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature)
    (unsat : Crush.SMT.CommandsUnsatisfiable (commands encoding source)) :
    Unsatisfiable source := by
  exact TranslationStatus.unsat_source (generate encoding source)
    (generate_proves encoding source) unsat

end Crush.Metatheory.VCG
