import Crush.Metatheory.Reification.Witness
import Crush.Metatheory.SMT.Guarded
import Crush.Metatheory.SMT.Soundness

/-!
# Proved verification-condition generation

This is the total proof-facing route after successful Lean-to-HO reification.
It runs the intrinsic flattened translation and the pure FO-to-SMT encoder. The
resulting status retains an exact representation theorem by construction.
-/

namespace Crush.Metatheory.VCG

open Defunctionalization.Flattened
open SMT.Datatype
open scoped Crush.Metatheory Crush.SMT

/-- The SMT encoder's complete translated result is the flattened complete
target theory for the same intrinsic source sentence. -/
theorem completeTheory_translate {signature : Signature}
    (source : Sentence signature) :
    SMT.completeTheory 𝓕⟦source⟧ = translatedTheory source := rfl

/-- Exact concrete commands generated by the total proved VCG route. -/
def commands {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) : Array Crush.SMT.Command :=
  SMT.encode encoding 𝓕⟦source⟧

/-- Ordinary declarations and assertions following the encoding's native
command prefix. -/
def commandBody {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) : Array Crush.SMT.Command :=
  SMT.theoryBody encoding
    (𝓕⟦source⟧.declarations.map SMT.ofDeclared)
    (SMT.completeTheory 𝓕⟦source⟧)

@[simp] theorem commands_split {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) :
    commands encoding source =
      encoding.nativeCommands ++ commandBody encoding source := rfl

/-- The proved VCG command sequence represents the complete flattened theory. -/
theorem commands_represents {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature) :
    SMT.TheoryRepresentation encoding (translatedTheory source)
      (commands encoding source) := by
  rw [← completeTheory_translate source]
  exact SMT.encode_translation encoding 𝓕⟦source⟧

/-! ## Guarded command generation -/

/-- Exact concrete commands for a guarded intrinsic VCG run. `derived` is the
certified recursive-definition segment, such as datatype `wf_T` commands. -/
def guardedCommands {signature : Signature}
    (guarding : SMT.Guarding (Symbol signature))
    (derived : Array Crush.SMT.Command) (source : Sentence signature) :
    Array Crush.SMT.Command :=
  guarding.theory derived
    (𝓕⟦source⟧.declarations.map SMT.ofDeclared)
    (translatedTheory source)

/-- Guarded generation retains exact declaration order and command syntax by
construction. -/
theorem guardedCommands_represents {signature : Signature}
    (guarding : SMT.Guarding (Symbol signature))
    (derived : Array Crush.SMT.Command) (source : Sentence signature) :
    SMT.GuardedTheoryRepresentation guarding derived (translatedTheory source)
      (guardedCommands guarding derived source) :=
  ⟨𝓕⟦source⟧.declarations.map SMT.ofDeclared,
    Crush.SMT.SameCommandSet.refl _⟩

/-- Unsatisfiability of commands from total proved VCG reflects to the
intrinsic HO sentence. -/
theorem commands_unsat_implies_source_unsat {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Sentence signature)
    (data : Reification.DataBridge signature)
    (native : EnvRepresentation encoding data.toModelEnv)
    (unsat : Crush.SMT.CommandsUnsatisfiable (commands encoding source)) :
    Datatype.Env.Unsatisfiable data.toModelEnv source := by
  exact SMT.commands_unsat_implies_source_unsat encoding native source
    (commands_represents encoding source) unsat

/-! ## Finite source theories -/

/-- Exact concrete commands for a finite intrinsic source theory translated
against one common signature. -/
def theoryCommands {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Theory signature) : Array Crush.SMT.Command :=
  SMT.encodeTheories encoding source

/-- The finite-theory VCG represents the combined flattened target theory. -/
theorem theoryCommands_represents {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Theory signature) :
    SMT.TheoryRepresentation encoding (translatedTheories source)
      (theoryCommands encoding source) :=
  SMT.encode_theories encoding source

/-- Exact guarded commands for a finite intrinsic source theory. -/
def guardedTheoryCommands {signature : Signature}
    (guarding : SMT.Guarding (Symbol signature))
    (derived : Array Crush.SMT.Command) (source : Theory signature) :
    Array Crush.SMT.Command :=
  guarding.theory derived (SMT.translatedDeclarations source)
    (translatedTheories source)

/-- Guarded finite-theory generation retains exact declarations and assertions
in source traversal order. -/
theorem guardedTheoryCommands_represents {signature : Signature}
    (guarding : SMT.Guarding (Symbol signature))
    (derived : Array Crush.SMT.Command) (source : Theory signature) :
    SMT.GuardedTheoryRepresentation guarding derived (translatedTheories source)
      (guardedTheoryCommands guarding derived source) :=
  ⟨SMT.translatedDeclarations source, Crush.SMT.SameCommandSet.refl _⟩

/-- Unsatisfiability of the finite-theory VCG reflects to the complete
intrinsic source theory. -/
theorem theoryCommands_unsat_implies_source_unsat {signature : Signature}
    (encoding : SMT.Encoding (Symbol signature))
    (source : Theory signature)
    (data : Reification.DataBridge signature)
    (native : EnvRepresentation encoding data.toModelEnv)
    (unsat : Crush.SMT.CommandsUnsatisfiable
      (theoryCommands encoding source)) :
    Datatype.Env.TheoryUnsatisfiable data.toModelEnv source := by
  exact SMT.commands_unsat_implies_source_theory_unsat encoding native source
    (theoryCommands_represents encoding source) unsat

end Crush.Metatheory.VCG
